### ISSUE TITLE
请问作者，使用Shadowsocks客户端是否支持使用lightsocks呢？

### ISSUE THREAD

**Issue by 0xhhhhh** [linw1995/lightsocks-python#13]
是否可以直接食用，还是要修改一些code?

**Comment by qmzhn** [comment]
伸手党读个代码有这么难么？

**Comment by 0xhhhhh** [comment]
> 伸手党读个代码有这么难么？

问你了嘛？

**Comment by celeron633** [comment]
很明显是不可能支持的，这个有点像很早初代版本的shadowsocks的协议，用的table置换加密，现在ss的协议都升级了好几次了，不可能兼容的。
