### ISSUE TITLE
無法執行

### ISSUE THREAD

**Issue by delphinuz** [linw1995/lightsocks-python#2]
File "lsserver.py", line 12
    def run_server(config: lsConfig.Config):
                         ^
SyntaxError: invalid syntax

python 是2.7.3

**Comment by linw1995** [comment]
lightsocks目前只在python3.6和go实现了。不好意思，没有python2.x的实现版本

**Comment by delphinuz** [comment]
謝謝。試著改一下，還不少要修改，只好放棄。
與你同一個城市，有機會再用微信溝通。

**Comment by linw1995** [comment]
十分荣幸，没错，py2.7要写出简单明了的async代码是十分麻烦的。

**Comment by delphinuz** [comment]
https://pypi.python.org/pypi/trollius

找一下這可以用於2.7的async，不過許多呼叫寫法是py3要改到py2.7要花不少時間。
