### ISSUE TITLE
運行發生以下錯誤

### ISSUE THREAD

**Issue by delphinuz** [linw1995/lightsocks-python#3]
Task exception was never retrieved
future: <Task finished coro=<LsServer.handleConn() done, defined at /home/cch/lightsocks-python-master/lightsocks/server.py:39> exception=gaierror(-2, 'Name or service not known')>
Traceback (most recent call last):
  File "/home/cch/lightsocks-python-master/lightsocks/server.py", line 74, in handleConn
    dstServer = socket.create_connection(dstAddress)
  File "/usr/local/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

安裝好3.6(3.4還不行)，試著執行出現以上問題。

**Comment by linw1995** [comment]
请更新到最新的版本。再尝试一下，若再出现问题请告诉我使用的详细过程，我好复现过程

**Comment by delphinuz** [comment]
仍一樣，只是大致上client<->server是通的。目前client端使用go x86版，不知與這有無關係。

過程就是執行  python3 lsserver.py -c ls.json

當client連上時，以上的錯誤訊息不時持續發生。

**Comment by linw1995** [comment]
实现这个py版本的时候只想着学习一下，也没在平时使用这个工具。如果没有具体的操作过程，我是很难复现这个异常的。🤣

**Comment by delphinuz** [comment]
看來好像是dns的問題，給作者參考。

**Comment by xtudbxk** [comment]
这是我修改的方法，
问题是出现在 lightsocks/server.py 文件上，
在121行时，我打印出 buf, 结果为 buf:bytearray(b'\x05\x01\x00\x03\x11beacons5.gvt2.com\x01\xbb'),
对照下面的代码，应该是ip在buf的起始位置不对，我的将 130左右的4改成了5，目前运行成功
你也可以打印下看下你的是不是这儿有问题，

#另，好像lsserver.py和lslocal.py里有些字符串前多了个 f ? 

给作者参考下 /doge

**Comment by linw1995** [comment]
@xtudbxk 字符串前加f是py3.6的feature。

谢谢指正🤣
