### ISSUE TITLE
学习

### ISSUE THREAD

**Issue by wadream** [linw1995/lightsocks-python#8]
你好，能知道我安装吗，linode vps CentOS 6.8 ，安装了python3.6，还是没法安装lightsocks-python？
能指导我吗，可以微信

**Comment by linw1995** [comment]
lightsocks只是用来学习一个简单实现，要用的话最好用shadowsocks。

**Comment by wadream** [comment]
你好，ssr目前已经废了，ip封了换ip也不行，能知道我架设 lightsocks-python 这个吗？能加你qq货微信吗？
qq35832581

**Comment by babyfiv5** [comment]
研究了一下代码，总结一下不知道对不对，希望您指点一下：lightsocks和shadowsocks的实现方法区别还挺大的，lightsocks主要利用async来处理异步和阻塞关系，而shadowsocks自己建立了event处理机制，相当于自己造了一个事件处理的轮子。在协议处理方面，lightsocks的握手信息是明文的，而shadowsocks是加密的？另外lightsocks使用的加密方式是类似原始shadowsocks中的table加密，不知道我说的对不对，希望指正。shadowsocks的代码有些复杂，读起来有些困难，有些理解不是很深
