### ISSUE TITLE
你好，我想问怎么写 android ios win 的客户端呢？

### ISSUE THREAD

**Issue by nanqinlang** [linw1995/lightsocks-python#9]
是不是就是把现有的 linux local 客户端，转换成对应其它平台的语言就行呢？

目前我的疑惑是，对应语言是什么呢？我猜：
- android：java
- ios：swift
- win：c#

**Comment by linw1995** [comment]
GUI客户端？大部分语言都可以写吧

**Comment by nanqinlang** [comment]
@linw1995  
也不是说非要 gui 啦
我就是想写个 android 的 apk 和 win 的 exe（双击运行是 cmd 样式的那种），但是不知道怎么写，完全没经验。。。

**Comment by linw1995** [comment]
这些对应的入门教程，网上很多呀。

**Comment by nanqinlang** [comment]
@linw1995  
嗯，所以就是想问有没有特别的注意事项（毕竟那些教程并不是教你做扶墙软件）

**Comment by autodataming** [comment]
@nanqinlang https://github.com/XanthusL/LightSocks-Android
